exclude: |
  (?x)^(
    Unity/.*\.meta|
    Unity/.*\.prefab|
    Unity/.*\.unity|
    Unity/.*\.xml
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the latest stable release
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-json
        exclude: ^Unity/
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: pretty-format-json
        exclude: ^Unity/
        args: ["--autofix"]
      - id: trailing-whitespace
